import { MAFScene, Layer } from '../schema/maf';

const framerEasingMap: Record<string, string> = {
  linear: '[0, 0, 1, 1]',
  easeOutQuad: '[0.25, 0.46, 0.45, 0.94]',
  easeOutCubic: '[0.33, 1, 0.68, 1]',
  easeOutBack: '[0.34, 1.56, 0.64, 1]',
  spring: '{ type: "spring", stiffness: 300, damping: 20 }',
  easeOutBounce: '{ type: "spring", stiffness: 400, damping: 10 }',
  easeOutElastic: '{ type: "spring", stiffness: 200, damping: 8 }',
};

function layerToFramer(layer: Layer): string {
  const sorted = [...layer.keyframes].sort((a, b) => a.time - b.time);
  if (sorted.length < 2) return '';

  const first = sorted[0].properties;
  const last = sorted[sorted.length - 1].properties;

  const initial: string[] = [];
  const animate: string[] = [];

  if (first.opacity !== undefined) initial.push(`opacity: ${first.opacity}`);
  if (last.opacity !== undefined) animate.push(`opacity: ${last.opacity}`);
  if (first.scale) initial.push(`scale: ${first.scale.x}`);
  if (last.scale) animate.push(`scale: ${last.scale.x}`);
  if (first.rotation) initial.push(`rotate: ${first.rotation}`);
  if (last.rotation) animate.push(`rotate: ${last.rotation}`);

  const dur = ((sorted[sorted.length - 1].time - sorted[0].time) / 1000).toFixed(2);
  const delay = (sorted[0].time / 1000).toFixed(2);
  const ease = framerEasingMap[sorted[0].easing] || '[0.33, 1, 0.68, 1]';

  const s = layer.style as any;
  let element = 'div';
  let extraStyle = '';
  if (layer.type === 'text') {
    element = 'p';
    extraStyle = `style={{ fontFamily: "${s.fontFamily}", fontSize: ${s.fontSize}, fontWeight: "${s.fontWeight}", color: "${s.fill}" }}`;
  } else if (layer.type === 'rect') {
    extraStyle = `style={{ width: ${s.width}, height: ${s.height}, background: "${s.fill}", borderRadius: ${s.borderRadius || 0} }}`;
  } else if (layer.type === 'circle') {
    extraStyle = `style={{ width: ${s.radius * 2}, height: ${s.radius * 2}, background: "${s.fill}", borderRadius: "50%" }}`;
  }

  return `
  {/* ${layer.name} */}
  <motion.${element}
    id="${layer.id}"
    initial={{ ${initial.join(', ')} }}
    animate={{ ${animate.join(', ')} }}
    transition={{ duration: ${dur}, delay: ${delay}, ease: ${ease} }}
    ${extraStyle}
  >${layer.type === 'text' ? s.content : ''}</motion.${element}>`;
}

export function exportFramer(scene: MAFScene): string {
  const components = scene.layers.map(layerToFramer).filter(Boolean).join('\n');

  return `import { motion } from "framer-motion";

// Generated by MAF Studio — ${scene.meta.name}
// ${scene.intent}

export function ${scene.meta.name.replace(/\s+/g, '')}Animation() {
  return (
    <div style={{
      width: ${scene.meta.canvas.width},
      height: ${scene.meta.canvas.height},
      background: "${scene.meta.background}",
      position: "relative",
      overflow: "hidden"
    }}>
${components}
    </div>
  );
}
`;
}
